// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: dummys.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createDummy = `-- name: CreateDummy :exec
INSERT INTO dummys(id, status, description)
VALUES ($1, $2, $3)
RETURNING (id, status, description, updated_at, created_at)
`

type CreateDummyParams struct {
	ID          uuid.UUID
	Status      TxStatus
	Description string
}

func (q *Queries) CreateDummy(ctx context.Context, arg CreateDummyParams) error {
	_, err := q.db.ExecContext(ctx, createDummy, arg.ID, arg.Status, arg.Description)
	return err
}
