name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Build
        run: go build ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout 10m

      - name: govulncheck
        uses: golang/govulncheck-action@v1
