name: Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install migrate tool
        run: go install github.com/rubenv/sql-migrate/...@latest

      - name: Build
        run: go build ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout 10m

      - name: Static analysis
        run: go vet ./...

      - name: Set up application environment
        run: make up && sleep 10

      - name: Apply migrations
        run: make migrations-up

      - name: Run tests
        run: go test -v -race ./...
